### ISSUE TITLE
Import LIWCalike into this package

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda.dictionaries#2]
Might as well swallow the [LIWCalike package](https://github.com/kbenoit/LIWCalike), and move its tests and functions here.

That package needs some serious tests, compared result for result to those from the [Java-based LIWCalike software](https://liwc.wpengine.com).

**Comment by stefan-mueller** [comment]
Happy to work on this next week. I'd start with

- [x] Moving the **LIWCalike** functions to **quanteda.corpora**
- [x] Check code 
- [x] Write a vignette that shows how **readtext**, a dictionary from **quanteda.corpora** and `quanteda.corpora::liwcalike()` can reproduce the [features](https://liwc.wpengine.com/compare-versions/) of the LIWC software. 
- [ ] Add more test for the `liwcalike()` function.

Anything else?

**Comment by kbenoit** [comment]
💯
