### ISSUE TITLE
Error while trying to install Quanteda.dictionaries as offline .zip file

### ISSUE THREAD

**Issue by rainiercito** [kbenoit/quanteda.dictionaries#30]
Good afternoon I tried to install the Quanteda.dictionaries and Quanteda.dictionaries offline and I couldn't. 

I tried using the install.packages("C:/ .../downloads/Quanteda.dictionaries-master", repos= NULL) , install.packages("C:/ .../downloads/Quanteda.dictionaries-master", repos= NULL, type = "win.library)  commands but they didn't work. I already installed via CRAN the Quanteda package without problem. 

I have the R 3.6.3 Version installed.  Any suggestion will be highly appreciated?

**Comment by kbenoit** [comment]
"didn't work" is pretty non-specific...

Can you not do:

```r
devtools::install_github("kbenoit/quanteda.dictionaries")
```
