### ISSUE TITLE
liwcalike() uses deprecated quanteda::tokens() argument 'remove_hyphens' instead of 'split_hyphens'

### ISSUE THREAD

**Issue by mrweiler** [kbenoit/quanteda.dictionaries#32]
'remove_hyphens' argument in quanteda::tokens() has been removed in commit 1fa0c69 (?) but is still used in quanteda.dictionaries::liwcalike() in lines 37 and 77 (https://github.com/kbenoit/quanteda.dictionaries/blob/master/R/liwcalike.R).

**Comment by kbenoit** [comment]
Fixed in 2c75e70
