### ISSUE TITLE
Parentheses column 0 if not all strings contain prentheses pairs.

### ISSUE THREAD

**Issue by DominikBaer95** [kbenoit/quanteda.dictionaries#36]
Dear Dr. Benoit,

thanks for the great package! 

I realized that when supplying a vector of strings to quanteda.dictionaries::liwcalike() and not all strings contain pairs of parentheses the whole "Parenth" column turns zero.

For example:
```
library(quanteda)
library(quanteda.dictionaries)

# All strings have parentheses

strings_1 <- c("(2386) TOP, Comment - YouTube", "Yeah: We the \"People\" have heard enough of the Sorry, (not sorry); from you!", " I understand the point (?) ...i.e. the current 'debacle'.")
quanteda.dictionaries::liwcalike(corpus(strings_1))
# => Parenth column correct

# One string without parentheses (i.e., 2368 in first string without parentheses, all else being equal)
strings_2 <- c("2386 TOP, Comment - YouTube", "Yeah: We the \"People\" have heard enough of the Sorry, (not sorry); from you!", " I understand the point (?) ...i.e. the current 'debacle'.")
quanteda.dictionaries::liwcalike(corpus(strings_2))
# => Parenth column zero for all entries. Yet, strings_2[2:3] do have pairs of parentheses => should not be zero?
```

Output:
![image](https://user-images.githubusercontent.com/75019577/161773885-f2508a78-8f07-4f0c-b5a8-fedde786cd40.png)

Is this expected behavior? 

Thank you sincerely,
Dominik

**Comment by DominikBaer95** [comment]
I think the problem might be in this call inside the function:

```
result[["Parenth"]] <-
        min(c(stringi::stri_count_fixed(x, "("),
              stringi::stri_count_fixed(x, ")"))) / result[["WC"]] * 100
```

Instead of computing the minimum number of parentheses pairs for each string it seems to compute the minimum over all strings (i.e. 0 if one string does not contain any parentheses pairs).

A possible fix might be to use the following call:
```
result[["Parenth"]] <-
    apply(cbind(stringi::stri_count_fixed(x, "("),
          stringi::stri_count_fixed(x, ")")), 1, "min") / result[["WC"]] * 100
```

Let me know what you think.

Thanks,
Dominik

**Comment by kbenoit** [comment]
Thanks so much for pointing this out Dominik. I fixed it by changing to `pmin()` on the two as vectors, since this is more efficient than `apply()` on a margin.

If you see any more discrepancies or errors please do let me know!

**Comment by DominikBaer95** [comment]
Thanks a lot for the quick fix! It works perfectly now :)
