### ISSUE TITLE
data_dictionary_Rauh gone?

### ISSUE THREAD

**Issue by LukasWallrich** [kbenoit/quanteda.dictionaries#37]
I just returned to this package after a while and my code broke - `data_dictionary_Rauh` does not seem to exist anymore. Is that a bug? I recognise that it might also be a licence issue - but if so, should it be deprecated rather than just disappear?

**Comment by ChRauh** [comment]
Cannot say anything about the package (even though I would love to see the dictionary featured therein, of course ;)), but in any case you can access the 'raw' dictionary under the following permanent link (to be converted to a quanteda dictionary object): https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/BKBXWD

**Comment by LukasWallrich** [comment]
Just in case someone else runs into this issue: for now, I've managed to get the dictionary back by reverting to an old version of this package: `devtools::install_github("kbenoit/quanteda.dictionaries@a310906")`

**Comment by stefan-mueller** [comment]
Thanks for raising this issue. `data_dictionary_Rauh` has been moved to the experimental package [**quanteda.sentiment**](https://github.com/quanteda/quanteda.sentiment) a while ago.

```r
# devtools::install_github("quanteda/quanteda.sentiment")

library(quanteda.sentiment)

summary(data_dictionary_Rauh)
#>              Length Class  Mode     
#> neg_negative 19750  -none- character
#> neg_positive 17330  -none- character
#> negative     19750  -none- character
#> positive     17330  -none- character
```
