### ISSUE TITLE
examples from README failing: missing data_dictionary_NRC

### ISSUE THREAD

**Issue by DSLituiev** [kbenoit/quanteda.dictionaries#39]
I tried to run the examples from you README:

```r
library("quanteda.dictionaries")

output_lsd <- liwcalike(quanteda.corpora::data_corpus_movies, 
                        dictionary = data_dictionary_NRC)

head(output_lsd)
```

and I am not able to find these two objects:
1. `Error in loadNamespace(x) : there is no package called ‘quanteda.corpora’`
2. `Error: object 'data_dictionary_NRC' not found`. I tried `quanteda.dictionaries:::data_dictionary_NRC`, still same issue.

Please advise

**Comment by kbenoit** [comment]
You would have needed to install the packages https://github.com/quanteda/quanteda.sentiment and https://github.com/quanteda/quanteda.corpora for that to work.

But I've now updated the README and vignettes not to require these additional packages.
